name: kicad-snap
version: "4.0.7-snap1"
grade: stable
summary: Electronic schematic and PCB design software
description: |
 Kicad is a suite of programs for the creation of printed circuit boards.
 It includes a schematic editor, a PCB layout tool, support tools and a
 3D viewer to display a finished & fully populated PCB.
 Kicad is made up of 5 main components
  * kicad - project manager
  * eeschema - schematic editor
  * pcbnew - PCB editor
  * gerbview - GERBER viewer
  * cvpcb - footprint selector for components
 Libraries
  * Both eeschema and pcbnew have library managers and editors for their
    components and footprints
  * You can easily create, edit, delete and exchange library items
  * Documentation files can be associated with components, footprints and key
    words, allowing a fast search by function
  * Very large libraries are available for schematic components and footprints
  * Most components have corresponding 3D models
confinement: strict

apps:
    bitmap2component:
        command: wrapper $SNAP/usr/bin/bitmap2component
        plugs: [home, locale-control, opengl, unity7]
    eeschema:
        command: wrapper $SNAP/usr/bin/eeschema
        plugs: [cups-control, home, locale-control, network, network-bind, opengl, unity7]
    gerbview:
        command: wrapper $SNAP/usr/bin/gerbview
        plugs: [cups-control, home, locale-control, opengl, unity7]
    kicad:
        command: wrapper $SNAP/usr/bin/kicad
        plugs: [cups-control, home, locale-control, network, network-bind, opengl, unity7]
    pcb-calculator:
        command: wrapper $SNAP/usr/bin/pcb_calculator
        plugs: [home, locale-control, opengl, unity7]
    pcbnew:
        command: wrapper $SNAP/usr/bin/pcbnew
        plugs: [cups-control, home, locale-control, network, network-bind, opengl, unity7]
    pl-editor:
        command: wrapper $SNAP/usr/bin/pl_editor
        plugs: [cups-control, home, locale-control, opengl, unity7]

parts:
    wrapper:
        source: .
        plugin: dump
        organize:
            wrapper: bin/wrapper

    kicad:
        source: https://github.com/KiCad/kicad-source-mirror/archive/4.0.7.zip
        source-subdir: kicad-source-mirror-4.0.7
        plugin: cmake
        configflags: [-DCMAKE_BUILD_TYPE=Release,
                      -DCMAKE_INSTALL_PREFIX=/usr,
                      -DDEFAULT_INSTALL_PATH=$SNAP/usr,
                      -DKICAD_SKIP_BOOST=ON,
                      -DKICAD_VERSION_EXTRA="snap1",
                      -DKICAD_SCRIPTING=ON,
                      -DKICAD_SCRIPTING_MODULES=ON,
                      -DKICAD_SCRIPTING_WXPYTHON=ON,
                      -DKICAD_USER_CONFIG_DIR=$SNAP_USER_COMMON]
        build-packages:
            - build-essential
            - grep
            - libboost-all-dev
            - libbz2-dev
            - libcairo2-dev
            - libcurl4-openssl-dev
            - libgl1-mesa-dev
            - libglew-dev
            - libglm-dev
            - libglu1-mesa-dev
            - libssl-dev
            - libwxbase3.0-dev
            - libwxgtk-webview3.0-dev
            - libwxgtk3.0-dev
            - libx11-dev
            - mesa-common-dev
            - pkg-config
            - python-dev
            - python-wxgtk3.0
            - python-wxgtk3.0-dev
            - swig3.0
        stage-packages:
            - python-wxgtk3.0
            - libpython2.7
        stage:
            - -usr/share/pkgconfig/shared-mime-info.pc
        after: [desktop-gtk2]

    doc:
        source: https://github.com/KiCad/kicad-doc/archive/4.0.7.zip
        source-subdir: kicad-doc-4.0.7
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr,
                      -DBUILD_FORMATS=html]
        build-packages:
            - asciidoc
            - dblatex
            - docbook-utils
            - gettext
            - liblocale-gettext-perl
            - libunicode-linebreak-perl
            - libxml2-utils
            - lmodern
            - pandoc
            - po4a
            - source-highlight
            - texlive-lang-all
            - texlive-xetex
            - ttf-freefont
            - xmlto

    footprints:
        source: http://downloads.kicad-pcb.org/libraries/kicad-footprints-4.0.7.tar.gz
        plugin: dump
        organize:
            ./*: usr/share/kicad/modules/

    i18n:
        source: https://github.com/KiCad/kicad-i18n/archive/4.0.7.zip
        source-subdir: kicad-i18n-4.0.7
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
        build-packages:
            - gettext

    library:
        source: https://github.com/KiCad/kicad-library/archive/4.0.7.zip
        source-subdir: kicad-library-4.0.7
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
